
#load "animation/animation.jai";
#load "log.jai";
#load "draw.jai";
#load "tilemap.jai";
#load "pixel_perfect_viewport.jai";
#load "spline.jai";
#load "bounds.jai";
#load "curve.jai";
#load "imgui/imgui.jai";
#load "imgui/imgui_canvas.jai";
#load "tools/math.jai";
#load "tools/filesystem.jai";
#load "tools/misc.jai";
#load "tools/json.jai";
#load "tools/aseprite.jai";
#load "tools/os.jai";
#load "statemachine.jai";
#load "serialization/serializer.jai";
#load "serialization/json_serializer.jai";
#load "serialization/reflection_serialization.jai";
#load "raylib_imgui.jai";

#load "resources/resource.jai";
#load "resources/spritesheet.jai";
#load "resources/texture_file.jai";
#load "resources/aseprite_file.jai";
#load "resources/sprite.jai";
#load "resources/animation.jai";

#scope_module

#import,dir "./modules/jaison";